# Generated by Django 3.1.5 on 2022-04-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_auto_20200424_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('ReviewId', models.AutoField(primary_key=True, serialize=False)),
                ('ClientName', models.CharField(max_length=250)),
                ('clientReview', models.TextField(max_length=2000)),
            ],
        ),
    ]
